# Generated by Django 4.0.5 on 2022-06-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.IntegerField(blank=True, null=True, verbose_name='รุ่น')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า')),
                ('full_name', models.CharField(max_length=150, verbose_name='ชื่อ-นามสกุล')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='หน่วยงาน')),
                ('mobile', models.CharField(max_length=20, verbose_name='เบอร์มือถือ')),
                ('status', models.CharField(blank=True, choices=[('AF', 'กองทัพอากาศ'), ('MT', 'กลาโหม'), ('RT', 'เกษียณ'), ('RS', 'ลาออก'), ('DT', 'ตาย')], default='AF', max_length=5, null=True, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name_plural': '',
            },
        ),
    ]
